config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # カリキュラム一覧
  root to: 'homes#top'

  # Bookers1 topページ
  get '/reviews_top', to: 'homes#reviews_top'

  # Bookers2 top aboutページ
  get '/again_top', to: 'homes#again_top'
  get '/again_about', to: 'homes#again_about'

  # HTML
  resources :html, only: %i[index]
  get '/html/responsive', to: 'html#responsive'
  # HTML開発スキルアップ
  get 'html/skillup', to: 'html#skillup'

  # Ruby
  resources :ruby, only: %i[index]

  # Bookers1
  resources :reviews, except: %i[new]

  # Bookers2
  resources :again_users, except: %i[new create destroy]
  resources :again_books, except: %i[new] do
    resource :again_favorites, only: %i[create destroy]
  end
end

app/models/again_book.rb
class AgainBook < ApplicationRecord
  belongs_to :user
  has_many :again_favorites, dependent: :destroy

  def again_favorited_by?(user)
    again_favorites.where(user_id: user.id).exists
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/again_favorite.rb
class AgainFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :again_book

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review_post.rb
class ReviewPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :again_books, dependent: :destroy
  has_many :again_favorites, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/again_books_controller.rb
class AgainBooksController < ApplicationController
  # Bookers2のコントローラー
  def index
    @books = AgainBook.all
    @book = AgainBook.new
    @user = current_user
  end

  def create
    @user = current_user
    @book = AgainBook.new(again_book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = 'You have created book successfully.'
      redirect_to again_book_path(@book)
    else
      @books = AgainBook.all
      render :index
    end
  end

  def show
    @newbook = AgainBook.new
    @book = AgainBook.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = AgainBook.find(params[:id])
    # 投稿がログイン中のユーザーと紐づいていなければマイページに遷移させる
    redirect_to again_user_path(current_user) unless @book.user == current_user
  end

  def update
    @book = AgainBook.find(params[:id])
    if @book.update(again_book_params)
      flash[:success] = 'You have updated book successfully.'
      redirect_to again_book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = AgainBook.find(params[:id])
    @book.destroy
    redirect_to again_books_path
  end

  private

  def again_book_params
    params.require(:again_book).permit(:title, :body)
  end
end

app/controllers/again_favorites_controller.rb
class AgainFavoritesController < ApplicationController

  def create
  end

  def destroy
  end

end

app/controllers/again_users_controller.rb
class AgainUsersController < ApplicationController
  # Bookers2のコントローラー
  def index
    @users = User.all
    @user = current_user
    @book = AgainBook.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.again_books
    @book = AgainBook.new
  end

  def edit
    @user = User.find(params[:id])
    # ログインユーザーと検索か編集ボタンを押したユーザーのIDが一致しなければマイページに遷移にさせる
    redirect_to again_user_path(current_user) unless @user == current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'You have updated user successfully.'
      redirect_to again_user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログインしていない場合top、about画面以外のページを表示させようとした時ログイン画面に遷移させる
  before_action :authenticate_user!, except: %i[again_top again_about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:success] = 'Signed in successfully.'
    again_user_path(resource)
  end

  def after_sign_up_path_for(resource)
    flash[:success] = 'Welcome! You have signed up successfully.'
    again_user_path(resource)
  end

  def after_sign_out_path_for(_resource)
     flash[:success] = 'Signed out successfully.'
    again_top_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # それぞれのトップページ用のコントローラー
  def top; end

  def reviews_top; end

  def again_top; end
end

app/controllers/html_controller.rb
class HtmlController < ApplicationController
  # HTMLのコントローラー
  # 2~9章表示
  def index; end

  # 10章表示
  def responsive; end

  # 開発スキルアップ
  def skillup; end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # Bookers1のコントローラー
  def index
    @post = ReviewPost.new
    @posts = ReviewPost.all
  end

  def create
    @post = ReviewPost.new(review_post_params)
    if @post.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to review_path(@post)
    else
      @posts = ReviewPost.all
      render :index
    end
  end

  def show
    @post = ReviewPost.find(params[:id])
  end

  def edit
    @post = ReviewPost.find(params[:id])
  end

  def update
    @post = ReviewPost.find(params[:id])
    if @post.update(review_post_params)
      flash[:notice] = 'Book was successfully update.'
      redirect_to review_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = ReviewPost.find(params[:id])
    post.destroy
    flash[:danger] = 'Book was successfully destroyed.'
    redirect_to reviews_path
  end

  private

  def review_post_params
    params.require(:review_post).permit(:title, :body)
  end
end

app/controllers/ruby_controller.rb
class RubyController < ApplicationController
  # Rubyのコントローラー
  def top; end

  def index; end
end

app/helpers/again_books_helper.rb
module AgainBooksHelper
end

app/helpers/again_favorites_helper.rb
module AgainFavoritesHelper
end

app/helpers/again_users_helper.rb
module AgainUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/html_helper.rb
module HtmlHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/ruby_helper.rb
module RubyHelper
end

app/views/again_books/_form.html.erb
<!-- Bookers2の新規投稿フォーム -->
<%= form_with model:again_book, url:'/again_books', local:true do |f| %>
  <%= render 'layouts/again_error_messages', model: f.object %>

  <div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: "form-control"%>
  </div>

  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  </div>
<% end %>

app/views/again_books/edit.html.erb
<!-- Bookers2の投稿編集画面 -->
<%= render "layouts/again_header" %>
<div class="container">
  <div class="row mt-3">
    <div class="mx-auto">
      <h1 class="col-12">Editing Book</h1>
      <%= form_with model:@book, url:"/again_books/#{@book.id}", local:true do |f| %>

        <div class="form-grop">
          <label>Title</label><br>
          <%= f.text_field :title, class:"form-control" %><br>
        </div>
        <div class="form-grop">
          <label>Opinion</label><br>
          <%= f.text_area :body, class:"form-control" %><br>
        </div>

        <div class="form-grop mb-3">
          <%= f.submit "Update Books", class:"btn btn-success" %><br>
        </div>
        <%= link_to "Show", again_book_path(@book) %>
        |
        <%= link_to "Back", again_books_path %>
      <% end %>
    </div>
  </div>
</div>
<%= render "layouts/again_footer" %>

app/views/again_books/index.html.erb
<!-- Bookers2の投稿一覧画面 -->
<%= render "layouts/again_header" %>
<div class="container px-5 px-sm-0">
  <div class="row mt-3">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'again_users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'again_books/form', again_book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <% user = User.find(book.user_id) %>
            <tr>
              <td>
                <%= link_to again_user_path(user.id) do %>
                  <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
                <% end %>
              </td>
              <td>
                <%= link_to again_book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render "layouts/again_footer" %>

app/views/again_books/show.html.erb
<!-- Bookers2の投稿詳細画面 -->
<%= render "layouts/again_header" %>
<p class="text-success"><%= flash[:success] %></p>
<div class="container px-5 px-sm-0">
  <div class="row mt-3">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'again_users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'again_books/form', again_book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <td>
          <%= link_to again_user_path(@user.id) do %>
            <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %><br>
            <%= @user.name%>
          <% end %>
        </td>
        <td>
          <%= link_to again_book_path(@book.id) do %>
            <%= @book.title %>
          <% end %>
        </td>
         <td><%= @book.body %></td>
        <% if @book.user_id == current_user.id %>
          <td><%= link_to "Edit", edit_again_book_path(@book), class:"btn btn-sm btn-success" %></td>
          <td><%= link_to "Destroy", again_book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class:"btn btn-sm btn-danger" %></td>
        <% end %>
      </table>
    </div>
  </div>
</div>
<%= render "layouts/again_footer" %>

app/views/again_users/_user.html.erb
<!-- Bookers2のユーザー情報 -->
<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg",size: "100x100" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <%= link_to (edit_again_user_path(user.id)), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %><% end %>
</div>

app/views/again_users/edit.html.erb
<!-- Bookers2のユーザー編集画面 -->
<%= render "layouts/again_header" %>
<div class="container">
  <div class="row mt-3">
    <div class="mx-auto">
      <h1 class="col-12">User info</h1>
      <%= form_with model:@user, url:"/again_users/#{@user.id}", local:true do |f| %>
        <%= render 'layouts/again_error_messages', model: f.object %>

        <div class="form-grop">
          <label>Name</label><br>
          <%= f.text_field :name, class:"form-control" %><br>
        </div>
        <div class="form-grop">
          <label>Image</label><br>
          <%= f.attachment_field :profile_image, class:"form-control-file" %><br>
        </div>

        <div class="form-grop">
          <label>Introduction</label><br>
          <%= f.text_area :introduction, class:"form-control" %><br>
        </div>

        <div class="form-grop">
          <%= f.submit "Update User", class:"btn btn-secondary" %><br>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "layouts/again_footer" %>

app/views/again_users/index.html.erb
<!-- Bookers2のユーザー一覧画面 -->
<%= render "layouts/again_header" %>
<div class="container px-5 px-sm-0">
  <div class="row mt-3">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'again_users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'again_books/form', again_book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", again_user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render "layouts/again_footer" %>

app/views/again_users/show.html.erb
<!-- Bookers2のユーザー詳細画面 -->
<%= render "layouts/again_header" %>
<p class="text-success"><%= flash[:success] %></p>
<div class="container px-5 px-sm-0">
  <div class="row mt-3">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'again_users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'again_books/form', again_book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <% user = User.find(book.user_id) %>
            <tr>
              <td>
                <%= link_to again_user_path(user) do %>
                  <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "50x50" %>
                <% end %>
              </td>
              <td>
                <%= link_to again_book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= render "layouts/again_footer" %>

app/views/homes/again_about.html.erb
<!-- Bookers2のaboutページ -->
<%= render "layouts/again_header" %>
<div class="container">
  <div class="row mt-3">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>
<%= render "layouts/again_footer" %>

app/views/homes/again_top.html.erb
<!-- Bookers2のtopページ -->
<span class="again-top-logo"><%= link_to 'Topページへ', root_path, class: "text-secondary" %></span>
<%= render "layouts/again_header" %>
<p class="text-success"><%= flash[:success] %></p>
<div class="container mt-3">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in"%>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/homes/reviews_top.html.erb
<!-- Bookers1のtopページ -->
<div class="container">
  <div class="row">
    <h1 class="col-12 mt-3"><%= link_to 'Topページ', root_path %><h1>
    <h3 class="col-12 font-weight-bold mt-3">ようこそBookersへ！</h3>
    <p class="offset-1 col-11 mt-3"><b>Bookers</b>では、さまざまな書籍にかんするあなたの意見や</p>
    <p class="offset-1 col-11 mt-3">印象を共有し交換する事ができます</p>
    <p class="offset-1 mt-3 start-btn"><%= link_to "start", reviews_path %></p>
  </div>
</div>

app/views/homes/top.html.erb
<!-- 全体のトップページ -->
<div class="container">
  <div class="row">
    <h1 class="col-12 mt-3">カリキュラム復習</h1>
    <div class="row">
      <div class="col-12">
        <ul>
          <li class="mt-3"><%= link_to "HTML(2~9章)", html_index_path %></li>
          <li class="mt-3"><%= link_to "HTML(10章)", html_responsive_path %></li>
          <li class="mt-3"><%= link_to "HTML開発スキルアップ", html_skillup_path %></li>
          <li class="mt-3"><%= link_to "Ruby", ruby_index_path %></li>
          <li class="mt-3"><%= link_to "Bookers1", reviews_top_path %></li>
          <li class="mt-3"><%= link_to "Bookers2", again_top_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/html/responsive.html.erb
<!-- HTML復習画面(レスポンシブ) -->
<div class="container">
  <div class="row">
    <h1 class="col-12 mt-3"><%= link_to 'Topページ', root_path %><h1>
    <h1 class="col-12">HTML復習</h1>
    <div class="row chapter-9">
    <h3 id="chapter9" class="mt-3 col-12">chapter9(レスポンシブ)</h3>
    <div class="chapter9-header"></div>
    <div class="chapter9-main">
      <div class="chapter9-main-left">
        <p class="chapter9-main-heading">step1</p>
        <div class="chapter9-main-left-image"></div>
        <h3 class="chapter9-title">タイトルが入ります</h3>
        <p>文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。</p>
      </div>
      <div class="chapter9-main-center">
        <p class="chapter9-main-heading">step2</p>
        <div class="chapter9-main-center-image"></div>
        <h3 class="chapter9-title">タイトルが入ります</h3>
        <p>文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。</p>
      </div>
      <div class="chapter9-main-right">
        <p class="chapter9-main-heading">step3</p>
        <div class="chapter9-main-right-image"></div>
        <h3 class="chapter9-title">タイトルが入ります</h3>
        <p>文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。文章が入ります。</p>
      </div>
    </div>
    <div class="chapter9-footer"></div>
  </div>
  </div>
</div>

app/views/html/skillup.html.erb
<span class="again-top-logo"><%= link_to 'Topページへ', root_path, class: "text-secondary" %></span>
<div class="su-header">
  <nav class="su-nav">
    <div class="su-nav-logo"></div>
    <ul class="su-ul">
      <li class="su-li">Portfolio</li>
      <li class="su-li">Feature</li>
      <li class="su-li">Profile</li>
      <li class="su-li">Contact</li>
    </ul>
  </nav>
</div>
<div class="su-main">
  <div class="su-main-visual">
    <div class="su-main-visual-heading">
      <h2>Lorem Ipsum</h2>
      <p class="main-visual-text">simple Dummy text of the printing</p>
    </div>
  </div>
  <div class="su-portfolio">
    <div class="su-portfolio-heading">Portfolio</div>
  </div>
</div>
<div class="su-footer">

</div>

app/views/reviews/_error_messages.html.erb
  <!-- Bookers1エラーメッセージ -->
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/reviews/edit.html.erb
<!-- Bookers1投稿編集画面 -->
<div class="container">
  <div class="row mt-3">
    <h3 class="col-12 font-weight-bold">Editing Book</h3>
    <div class="col-12"><%= render 'error_messages', post: @post %></div>
    <%= form_with model:@post, url:"/reviews/#{@post.id}", local:true do |f| %>
      <h6 class="col-12">title</h6>
      <%= f.text_field :title, class: "col-12" %>
      <h6 class="mt-3 col-12">body</h6>
      <%= f.text_area :body, class: "col-12" %><br>
      <%= f.submit 'Update Book', class: "mt-2" %>
    <% end %>
    <div class="mt-3 col-12">
      <span class="review-btn"><%= link_to "Show", review_path(@post) %></span>
      |
      <span class="review-btn"><%= link_to "Back", reviews_path %></span>
    </div>
  </div>
</div>

app/views/reviews/index.html.erb
<!-- Bookers1投稿一覧画面 -->
<div class="container">
  <div class="row">
    <h1 class="col-12 mt-3"><%= link_to 'Topページ', root_path %><h1>
    <p class="bookers1-logo col-12"><%= link_to "Bookers1 Top", reviews_top_path %></p>
  </div>
  <div class="row">
    <p class="flash-message text-success"><%= flash[:notice] %></p>
    <p class="flash-message text-danger"><%= flash[:danger] %></p>
    <h3 class="col-12">Books</h3>
  </div>
  <div class="row">
    <table class="col-12">
      <thead>
        <tr>
          <th>Title</th>
          <th>Body</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td class="mt-3"><%= post.title %></td>
            <td class="mt-3"><%= post.body %></td>
            <td>
              <span class="review-btn mr-1"><%= link_to "show", review_path(post), class: "review-btn" %></span>
              <span class="review-btn mr-1"><%= link_to "edit", edit_review_path(post), class: "review-btn" %></span>
              <span class="review-btn"><%= link_to "destroy", review_path(post), method: :delete, "data-confirm" => "本当に削除しますか？" %></span>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row">
      <h5 class="col-12 mt-3 font-weight-bold">New Book</h5>
      <div class="col-12"><%= render 'error_messages', post: @post %></div>
      <%= form_with model:@post, url:'/reviews', local:true do |f| %>
        <h6 class="col-12">Title</h6>
        <%= f.text_field :title, class: "col-12" %>
        <h6 class="mt-3 col-12">Body</h6>
        <%= f.text_area :body, class: "col-12" %><br>
        <%= f.submit 'Create Book', class: "mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<!-- Bookers1投稿詳細画面 -->
<div class="container">
  <p class="flash-message text-success"><%= flash[:notice] %></p>
  <div class="row">
    <div class="mt-5 col-12"><b>Title:</b> <%= @post.title %></div>
    <div class="mt-3 col-12"><b>Body:</b> <%= @post.body %></div>
  </div>
  <div class="mt-3">
    <span class="review-btn"><%= link_to "Edit", edit_review_path(@post) %></span>
    |
    <span class="review-btn"><%= link_to "Back", reviews_path, class: "review-btn" %></span>
  </div>
</div>

app/views/ruby/top.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-12 mt-3"><%= link_to 'Topページ', root_path %><h1>
  </div>
</div>