config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # カリキュラム一覧
  root to: 'homes#top'

  # Bookers1 topページ
  get '/reviews_top', to: 'homes#reviews_top'

  # Bookers2 top aboutページ
  get '/again_top', to: 'homes#again_top'
  get '/again_about', to: 'homes#again_about'

  # HTML
  resources :html, only: %i[index]
  get '/html/responsive', to: 'html#responsive'
  # HTML開発スキルアップ
  get 'html/skillup', to: 'html#skillup'

  # Ruby
  resources :ruby, only: %i[index]

  # Bookers1
  resources :reviews, except: %i[new]

  # Bookers2
  resources :again_users, except: %i[new create destroy]
  resources :again_books, except: %i[new] do
    resource :again_favorites, only: %i[create destroy]
  end
end

app/models/again_book.rb
class AgainBook < ApplicationRecord
  belongs_to :user
  has_many :again_favorites, dependent: :destroy

  def again_favorited_by?(user)
    again_favorites.where(user_id: user.id).exists
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/again_favorite.rb
class AgainFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :again_book

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review_post.rb
class ReviewPost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :again_books, dependent: :destroy
  has_many :again_favorites, dependent: :destroy

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/again_books_controller.rb
class AgainBooksController < ApplicationController
  # Bookers2のコントローラー
  def index
    @books = AgainBook.all
    @book = AgainBook.new
    @user = current_user
  end

  def create
    @user = current_user
    @book = AgainBook.new(again_book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = 'You have created book successfully.'
      redirect_to again_book_path(@book)
    else
      @books = AgainBook.all
      render :index
    end
  end

  def show
    @newbook = AgainBook.new
    @book = AgainBook.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = AgainBook.find(params[:id])
    # 投稿がログイン中のユーザーと紐づいていなければマイページに遷移させる
    redirect_to again_user_path(current_user) unless @book.user == current_user
  end

  def update
    @book = AgainBook.find(params[:id])
    if @book.update(again_book_params)
      flash[:success] = 'You have updated book successfully.'
      redirect_to again_book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = AgainBook.find(params[:id])
    @book.destroy
    redirect_to again_books_path
  end

  private

  def again_book_params
    params.require(:again_book).permit(:title, :body)
  end
end

app/controllers/again_users_controller.rb
class AgainUsersController < ApplicationController
  # Bookers2のコントローラー
  def index
    @users = User.all
    @user = current_user
    @book = AgainBook.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.again_books
    @book = AgainBook.new
  end

  def edit
    @user = User.find(params[:id])
    # ログインユーザーと検索か編集ボタンを押したユーザーのIDが一致しなければマイページに遷移にさせる
    redirect_to again_user_path(current_user) unless @user == current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'You have updated user successfully.'
      redirect_to again_user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログインしていない場合top、about画面以外のページを表示させようとした時ログイン画面に遷移させる
  before_action :authenticate_user!, except: %i[again_top again_about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    flash[:success] = 'Signed in successfully.'
    again_user_path(resource)
  end

  def after_sign_up_path_for(resource)
    flash[:success] = 'Welcome! You have signed up successfully.'
    again_user_path(resource)
  end

  def after_sign_out_path_for(_resource)
     flash[:success] = 'Signed out successfully.'
    again_top_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # それぞれのトップページ用のコントローラー
  def top; end

  def reviews_top; end

  def again_top; end
end

app/controllers/html_controller.rb
class HtmlController < ApplicationController
  # HTMLのコントローラー
  # 2~9章表示
  def index; end

  # 10章表示
  def responsive; end

  # 開発スキルアップ
  def skillup; end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # Bookers1のコントローラー
  def index
    @post = ReviewPost.new
    @posts = ReviewPost.all
  end

  def create
    @post = ReviewPost.new(review_post_params)
    if @post.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to review_path(@post)
    else
      @posts = ReviewPost.all
      render :index
    end
  end

  def show
    @post = ReviewPost.find(params[:id])
  end

  def edit
    @post = ReviewPost.find(params[:id])
  end

  def update
    @post = ReviewPost.find(params[:id])
    if @post.update(review_post_params)
      flash[:notice] = 'Book was successfully update.'
      redirect_to review_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    post = ReviewPost.find(params[:id])
    post.destroy
    flash[:danger] = 'Book was successfully destroyed.'
    redirect_to reviews_path
  end

  private

  def review_post_params
    params.require(:review_post).permit(:title, :body)
  end
end

app/controllers/ruby_controller.rb
class RubyController < ApplicationController
  # Rubyのコントローラー
  def top; end

  def index; end
end

app/helpers/again_books_helper.rb
module AgainBooksHelper
end

app/helpers/again_favorites_helper.rb
module AgainFavoritesHelper
end

app/helpers/again_users_helper.rb
module AgainUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/html_helper.rb
module HtmlHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/ruby_helper.rb
module RubyHelper
end

app/views/layouts/_again_error_messages.html.erb
<div id="error_explanation">
  <% if model.errors.any? %>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/_again_footer.html.erb
<!-- Bookers2フッター -->
<footer>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_again_header.html.erb
<!-- Bookers2ヘッダー -->
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to again_top_path, class:"navbar-brand" do %>
      <span>Bookers</span>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-expanded="false" aria-controls="navbarNavDropdown" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li><%= link_to ' Home', again_user_path(current_user.id), class:"fas fa-home nav-link text-light font-weight-bold"%></li>
          <li><%= link_to " Users", again_users_path, class:"fas fa-users nav-link text-light font-weight-bold" %></li>
          <li><%= link_to ' Books', again_books_path, class:"fas fa-book-open nav-link text-light font-weight-bold" %></li>
          <li><%= link_to " logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light font-weight-bold" %></li>
        </ul>
        <% else %>
        <ul class="navbar-nav ml-auto">
          <li><%= link_to ' Home', again_top_path, class:"fas fa-home nav-link text-light font-weight-bold"%></li>
          <li><%= link_to " About", again_about_path, class:"fas fa-link nav-link text-light font-weight-bold" %></li>
          <li><%= link_to " sign up", new_user_registration_path, class:"fas fa-user-plus nav-link text-light font-weight-bold" %></li>
          <li><%= link_to " login", new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light font-weight-bold" %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DmmCurriculum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1.0">

    <script src="https://kit.fontawesome.com/685fb692d8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>